name: Delete M3U files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v5

      - name: Borrar archivos m3u
        run: |
          find . -type f -name "*.m3u" -delete

      - name: Guardar cambios
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          git add -A

          git commit -m "Eliminar archivos m3u" || echo "No hay cambios"

          git push
