name: Ejecutar PHP una vez

on:
  workflow_dispatch: # Permite ejecuci칩n manual en GitHub Actions

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP
        run: sudo apt-get install -y php

      - name: Ejecutar script PHP
        run: php replacex.php

      - name: Verificar estado de git
        run: git status

      - name: Agregar archivos nuevos y modificados
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .  # Asegura que TODOS los archivos sean a침adidos
          git commit -m "Actualizaci칩n autom치tica de archivos .m3u" || echo "Sin cambios para commitear"
          
      - name: Push de cambios
        run: |
          git push origin main || echo "No se pudo hacer push"
